export default [
  {
    id: 55,
    name: "Isometric",
    is_visible: true,
    created_at: "2022-09-29T23:05:44.907415+00:00",
    updated_at: "2022-09-29T23:05:44.907415+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/isometric.jpeg",
    is_premium: false,
    model_type: "diffusion",
    is_new: true,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAdEAACAgMAAwAAAAAAAAAAAAABAgMEAAURBiFx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAXEQEAAwAAAAAAAAAAAAAAAAAAAREx/9oADAMBAAIRAxEAPwCf3m4mrUPHyKurkexq4rcjy66BiXlZpG51PSgvwAcAAH0sYw0vOv/Z"
  },
  {
    id: 53,
    name: "Analogue",
    is_visible: true,
    created_at: "2022-09-20T17:25:26.365859+00:00",
    updated_at: "2022-09-20T17:25:26.365859+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/analogue.png",
    is_premium: false,
    model_type: "diffusion",
    is_new: true,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAeEAABBAIDAQAAAAAAAAAAAAACAAEDBQQhESNRcf/EABUBAQEAAAAAAAAAAAAAAAAAAAME/8QAGBEBAQEBAQAAAAAAAAAAAAAAAQIDAJH/2gAMAwEAAhEDEQA/AJGS0nsKihLKCEnhrMeAOttCI659+uiIoWqFB48cc2BZPO//2Q=="
  },
  {
    id: 54,
    name: "Retro-Futurism",
    is_visible: true,
    created_at: "2022-09-20T17:25:26.365859+00:00",
    updated_at: "2022-09-20T17:25:26.365859+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/retrofuturism.png",
    is_premium: false,
    model_type: "diffusion",
    is_new: true,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAgEAACAgEDBQAAAAAAAAAAAAABAgADBAUGBxEhIiRR/8QAFQEBAQAAAAAAAAAAAAAAAAAABAX/xAAbEQACAgMBAAAAAAAAAAAAAAABAgADBBGRMv/aAAwDAQACEQMRAD8AmA5M3NpPrYuVjMGJuey7Eqsssd/NizMpJ7t0HwACIiFW+3Xo9MtPg4xYk1rwT//Z"
  },
  {
    id: 52,
    name: "HDR",
    is_visible: true,
    created_at: "2022-09-12T19:05:50.064159+00:00",
    updated_at: "2022-09-12T19:05:50.064159+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/hdr.png",
    is_premium: false,
    model_type: "diffusion",
    is_new: true,
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAP0lEQVR4nAE0AMv/AAANHaXA0s7p+wEWJADr/v8zSVgWLjzE2uoAg5alc4eYc4eXZ3iIACM8TmJxf36MmiM8T2QTFqxVCeZcAAAAAElFTkSuQmCC"
  },
  {
    id: 50,
    name: "Paint",
    is_visible: true,
    created_at: "2022-09-12T19:05:50.064159+00:00",
    updated_at: "2022-09-12T19:05:50.064159+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/paint.png",
    is_premium: false,
    model_type: "diffusion",
    is_new: false,
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAPUlEQVR4nGOwj3IqidZ7+X9aeoQ7AwNDTO+ihEd3MtsSzRg8SopsPXwqJ2S4O0cw1E6Kjq4LcM9JNo33BAALDxNkjurzxAAAAABJRU5ErkJggg=="
  },
  {
    id: 49,
    name: "Polygon",
    is_visible: true,
    created_at: "2022-09-07T17:18:40.837099+00:00",
    updated_at: "2022-09-07T17:18:40.837099+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/polygon.png",
    is_premium: false,
    model_type: "diffusion",
    is_new: false,
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAP0lEQVR4nAE0AMv/APRKEP/l4P+/wmkpHgBUSCOEi49RX15apJcAaePHIhsYdlhbSQAbAJr/6uT06s2EmVMAFn5aF9BBXh3lAAAAAElFTkSuQmCC"
  },
  {
    id: 48,
    name: "Gouache",
    is_visible: true,
    created_at: "2022-09-01T19:46:46.989647+00:00",
    updated_at: "2022-09-01T19:46:46.989647+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/gouache.png",
    is_premium: false,
    model_type: "diffusion",
    is_new: false,
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAP0lEQVR4nAE0AMv/ANv//2KVtMZuKywgXQCc3elZVW2RAAAAAE8Aib3gADV4MgAVDAttAHyf0CdxtVwiLhMAPDxMErvHTtf7AAAAAElFTkSuQmCC"
  },
  {
    id: 32,
    name: "Realistic",
    is_visible: true,
    created_at: "2022-06-23T04:32:45.159315+00:00",
    updated_at: "2022-08-31T23:09:37.641991+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/realistic.jpeg",
    is_premium: false,
    model_type: "diffusion",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAT/xAAdEAABBQEAAwAAAAAAAAAAAAABAAIDBAURBiEx/8QAFAEBAAAAAAAAAAAAAAAAAAAABf/EABkRAAIDAQAAAAAAAAAAAAAAAAECAAMxEf/aAAwDAQACEQMRAD8Ah186v5ZBla27GyzdmpRhz3MafQJ4B0fEREetrgaYiUXuT//Z"
  },
  {
    id: 45,
    name: "Comic",
    is_visible: true,
    created_at: "2022-08-25T18:18:21.464769+00:00",
    updated_at: "2022-08-31T23:07:37.641991+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/comic.png",
    is_premium: false,
    model_type: "diffusion",
    is_new: false,
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAOUlEQVR4nGP4f6PpdIVXqLqYpyQbw//dWefa4+QZGCJV+BkcZfiNpUXUGRgsGcB4oatklzqrEwMDALA2DMHmCac1AAAAAElFTkSuQmCC"
  },
  {
    id: 47,
    name: "Line-Art",
    is_visible: true,
    created_at: "2022-08-31T23:09:37.641991+00:00",
    updated_at: "2022-08-31T23:06:37.641991+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/lineart.png",
    is_premium: false,
    model_type: "diffusion",
    is_new: false,
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAP0lEQVR4nAE0AMv/AG9vctHS1J6enwAAAAB9fX78/v/Oz9BIRkgAODg5i4uMsLCx09PTABQTFL7Awvb298vLy6mEG+vFsMeuAAAAAElFTkSuQmCC"
  },
  {
    id: 40,
    name: "Malevolent",
    is_visible: true,
    created_at: "2022-07-19T17:38:41.399719+00:00",
    updated_at: "2022-08-31T23:04:37.641991+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/malevolent.jpeg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAdEAACAgMAAwAAAAAAAAAAAAABAgMEAAURBhKB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAP/xAAYEQADAQEAAAAAAAAAAAAAAAAAAhEBMf/aAAwDAQACEQMRAD8Aok1q+OUqdHU29jBTMImSFbkqpF7EkqoVgAO9P04xjKzArtOn/9k="
  },
  {
    id: 44,
    name: "Meme",
    is_visible: true,
    created_at: "2022-08-05T23:30:32.583696+00:00",
    updated_at: "2022-08-31T23:02:37.641991+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/minion.jpeg",
    is_premium: false,
    model_type: "meme",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAP/xAAfEAABAgcBAQAAAAAAAAAAAAABAAMCBAUGERIhFDH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBv/EABgRAQADAQAAAAAAAAAAAAAAAAEAAgMR/9oADAMBAAIRAxEAPwClrXNUaw1URPFiLwzzskzq0IcNQEag4+np6iIpraoXQIPZ/9k="
  },
  {
    id: 35,
    name: "Throwback",
    is_visible: true,
    created_at: "2022-07-15T20:09:57.313869+00:00",
    updated_at: "2022-07-26T07:17:17.596279+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/throwback.jpg",
    is_premium: false,
    model_type: "diffusion",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAeEAACAgICAwAAAAAAAAAAAAABAwACBhEEBRMxgf/EABUBAQEAAAAAAAAAAAAAAAAAAAYH/8QAHREAAQQCAwAAAAAAAAAAAAAAAQACAwQREiEjkf/aAAwDAQACEQMRAD8AqORh+Mqe1Jx7q2UVe61+RAJrUWIA37P3ZiIk3ku2dj2O9KYiJmBwF//Z"
  },
  {
    id: 3,
    name: "No Style",
    is_visible: true,
    created_at: "2021-10-12T19:08:51.884459+00:00",
    updated_at: "2022-07-19T17:35:41.399719+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/no-style-1.jpg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAO0lEQVR4nGOQ4pbQkddSk1KV5BRn0JHXOrHn2O833/WVdRl0FbR+v/l+et9JEEeSU9xEw9hIxUCCQwwAhFMPFxHQKOYAAAAASUVORK5CYII="
  },
  {
    id: 22,
    name: "Ghibli",
    is_visible: true,
    created_at: "2022-03-08T04:49:16.982168+00:00",
    updated_at: "2022-07-19T17:33:41.399719+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/ghibli.jpg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAT/xAAdEAACAQUBAQAAAAAAAAAAAAABAgMABAURITEG/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAbEQABBAMAAAAAAAAAAAAAAAACAAEDETEykf/aAAwDAQACEQMRAD8At+XyV9jMc8dpc6EsrTOZIIpWZm1slmUk+ADvAAPBSlKiU0l7P1Iha8L/2Q=="
  },
  {
    id: 28,
    name: "Melancholic",
    is_visible: true,
    created_at: "2022-06-04T19:12:22.332439+00:00",
    updated_at: "2022-07-19T17:31:41.399719+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/melancholic.jpeg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAdEAACAgMAAwAAAAAAAAAAAAACAwABBAUREmGR/8QAFAEBAAAAAAAAAAAAAAAAAAAABP/EABURAQEAAAAAAAAAAAAAAAAAAAAx/9oADAMBAAIRAxEAPwCE2Cg3GQt+1EMt68bHULHAJF40hfK7de7+xEQMIf/Z"
  },
  {
    id: 39,
    name: "Pandora",
    is_visible: true,
    created_at: "2022-07-19T17:38:41.399719+00:00",
    updated_at: "2022-07-19T17:30:41.399719+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/pandora.jpeg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAdEAACAwACAwAAAAAAAAAAAAABAwACBAUGBzFR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgT/xAAXEQEBAQEAAAAAAAAAAAAAAAABAgAx/9oADAMBAAIRAxEAPwCUjyb2vEtCsXLac2cISKJS5laUAXWoAAt8qPcREREvTWSCG//Z"
  },
  {
    id: 36,
    name: "Daydream",
    is_visible: true,
    created_at: "2022-07-15T20:09:57.313869+00:00",
    updated_at: "2022-07-13T20:09:57.313869+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/daydream.jpeg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAeEAACAgICAwAAAAAAAAAAAAABAgMEAAUGIRMiQf/EABUBAQEAAAAAAAAAAAAAAAAAAAQF/8QAFhEAAwAAAAAAAAAAAAAAAAAAAAEx/9oADAMBAAIRAxEAPwCa8h5D5YdNZvanU3rFnXxSNJagLle2UIvt0oCgAfMYxkl0Yof/2Q=="
  },
  {
    id: 17,
    name: "Provenance",
    is_visible: true,
    created_at: "2022-01-17T22:10:36.750442+00:00",
    updated_at: "2022-07-11T20:09:57.313869+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/provenance-thumbnail-8.jpeg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAeEAABBAIDAQAAAAAAAAAAAAABAAIDEgQRBQYHIf/EABUBAQEAAAAAAAAAAAAAAAAAAAEE/8QAGREAAwADAAAAAAAAAAAAAAAAAAECEiFR/9oADAMBAAIRAxEAPwCL8r6H2CZmEZslsmoKtuC6ou/4CTvSIiqwngzpI//Z"
  },
  {
    id: 34,
    name: "Arcane",
    is_visible: true,
    created_at: "2022-07-03T07:50:30.092175+00:00",
    updated_at: "2022-07-03T07:50:30.092175+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/arcane.jpeg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAT/xAAfEAABBAICAwAAAAAAAAAAAAABAAIDBQQREhMhIkH/xAAVAQEBAAAAAAAAAAAAAAAAAAAEBf/EABYRAQEBAAAAAAAAAAAAAAAAAAABEf/aAAwDAQACEQMRAD8AirbG5vWTZDL+2qWRydIx6zI6YfDQeXHR9iSdn6iIhRTyP//Z"
  },
  {
    id: 31,
    name: "Toasty",
    is_visible: true,
    created_at: "2022-06-09T07:48:59.135897+00:00",
    updated_at: "2022-06-09T07:48:59.135897+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/toasty.jpeg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAgEAACAgEDBQAAAAAAAAAAAAABBAACBQMGIQcRE1GB/8QAFQEBAQAAAAAAAAAAAAAAAAAABAX/xAAYEQACAwAAAAAAAAAAAAAAAAAAAQIRMf/aAAwDAQACEQMRAD8AhN+dQs/gMyujiNVZVWqS5FKr0Pc+Mc8j0APkREHHClSP/9k="
  },
  {
    id: 27,
    name: "Radioactive",
    is_visible: true,
    created_at: "2022-06-01T20:10:06.190673+00:00",
    updated_at: "2022-06-01T20:10:06.190673+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/radioactive.jpeg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAT/xAAgEAABAwQCAwAAAAAAAAAAAAADAAEEAgUGEgcRIVFh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAT/xAAYEQEBAAMAAAAAAAAAAAAAAAABAAIDEv/aAAwDAQACEQMRAD8ApwnHInIeNxbvdTS4ZQ9wRAgl1FQIT60szV7O3j716ZkRFM5IzYHTf//Z"
  },
  {
    id: 29,
    name: "Transitory",
    is_visible: true,
    created_at: "2022-06-06T03:57:34.212952+00:00",
    updated_at: "2022-05-13T12:53:14.897120+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/transitory.jpeg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAeEAACAwABBQAAAAAAAAAAAAACAwABBAUGERMhQf/EABUBAQEAAAAAAAAAAAAAAAAAAAMF/8QAGBEBAAMBAAAAAAAAAAAAAAAAAQACEQP/2gAMAwEAAhEDEQA/AILk+pOSc4BzHnx5UD4E5lZVGCgErqhG2CRdvX0riIglKpqSodbhgs//2Q=="
  },
  {
    id: 15,
    name: "S.Dali",
    is_visible: true,
    created_at: "2022-01-07T03:36:37.058860+00:00",
    updated_at: "2022-03-08T05:09:17.414243+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/salvador.jpg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAcEAACAwEAAwAAAAAAAAAAAAACAwABBAUiQWH/xAAUAQEAAAAAAAAAAAAAAAAAAAAF/8QAHBEAAQQDAQAAAAAAAAAAAAAAAQACA5ETFCEx/9oADAMBAAIRAxEAPwCL7ff0jpTb83O1vNCyZo14lOc0rGvIzIbsr+36qoiIRsSjxxspbBGelopf/9k="
  },
  {
    id: 14,
    name: "Etching",
    is_visible: true,
    created_at: "2021-12-17T03:41:27.859971+00:00",
    updated_at: "2022-03-08T05:09:17.414243+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/etching_tn.jpeg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAgEAABAwMFAQAAAAAAAAAAAAABAAMRAgQFBgcSITGh/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AJuP3U1Lb4TFFt22h21pcIqZ5QZIgSfOvpREQJ//2Q=="
  },
  {
    id: 13,
    name: "Baroque",
    is_visible: true,
    created_at: "2021-12-17T03:41:27.859971+00:00",
    updated_at: "2022-03-08T05:09:17.414243+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/budha.jpg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAdEAACAwACAwAAAAAAAAAAAAABBAACAwUGETFh/8QAFAEBAAAAAAAAAAAAAAAAAAAABf/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwCZdp7G01zGjbivHNMM1rtpoynnrbyR6BsCQPkREFpZ/9k="
  },
  {
    id: 11,
    name: "Mystical",
    is_visible: true,
    created_at: "2021-12-03T00:55:35.554480+00:00",
    updated_at: "2022-03-08T05:09:17.414243+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/mystical_2.jpg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAfEAABBAICAwAAAAAAAAAAAAABAAIDBAUhBhIHEzH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBP/EABcRAQEBAQAAAAAAAAAAAAAAAAECABH/2gAMAwEAAhEDEQA/AILMebuZ491VmPt160MkAl9TYezWkk6b2JIGhr4iInleahqh4O//2Q=="
  },
  {
    id: 10,
    name: "Dark Fantasy",
    is_visible: true,
    created_at: "2021-10-13T20:41:45.269258+00:00",
    updated_at: "2022-03-08T05:09:17.414243+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/dark-fantasy.jpg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAfEAACAgIBBQAAAAAAAAAAAAABAgADBAUhBxETMlH/xAAVAQEBAAAAAAAAAAAAAAAAAAAEBf/EABcRAQEBAQAAAAAAAAAAAAAAAAEAAiH/2gAMAwEAAhEDEQA/AJx1DzL9Nv11uHdecPHqAorsudvEjMzitefVSxAHztyYiJTQgZeX/9k="
  },
  {
    id: 9,
    name: "Psychic",
    is_visible: true,
    created_at: "2021-10-12T19:13:52.463282+00:00",
    updated_at: "2022-03-08T05:09:17.414243+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/psychic-dystopia.jpg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAP/xAAeEAACAgICAwAAAAAAAAAAAAABAgMEAAUGERUhUf/EABUBAQEAAAAAAAAAAAAAAAAAAAAD/8QAGBEBAQEBAQAAAAAAAAAAAAAAAQIAAzL/2gAMAwEAAhEDEQA/AK7LUaq/ybkHktZVuT17zVhPKCJJFREALlSAW+nr3jGMVVCg6vT07//Z"
  },
  {
    id: 7,
    name: "HD",
    is_visible: true,
    created_at: "2021-10-12T19:13:23.239102+00:00",
    updated_at: "2022-03-08T05:09:17.414243+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/hd.jpg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAdEAACAgMAAwAAAAAAAAAAAAABAgMRAAQFBhIU/8QAFAEBAAAAAAAAAAAAAAAAAAAABv/EABkRAQACAwAAAAAAAAAAAAAAAAEAAhETIf/aAAwDAQACEQMRAD8AnWv5TLowpEvJ4mxGUV0+zSXYaMFQfRWktggN0LNXjGMa66vUhPLP/9k="
  },
  {
    id: 6,
    name: "Vibrant",
    is_visible: true,
    created_at: "2021-10-12T19:12:56.385600+00:00",
    updated_at: "2022-03-08T05:09:17.414243+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/vibrant.jpg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAeEAABBAIDAQAAAAAAAAAAAAABAAIDBBEhBQYSFP/EABUBAQEAAAAAAAAAAAAAAAAAAAQG/8QAHBEAAgEFAQAAAAAAAAAAAAAAAQIAAwQSITHh/9oADAMBAAIRAxEAPwCZ9r5Ww2zUt1vFaa/X+q0YhqaZ0jw6Qg5wSGjQwNaAREQLcB6YZtn2XOCjgn//2Q=="
  },
  {
    id: 5,
    name: "Fantasy Art",
    is_visible: true,
    created_at: "2021-10-12T19:11:00.892700+00:00",
    updated_at: "2022-03-08T05:09:17.414243+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/fantasy-art.jpg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAL/xAAdEAACAgMAAwAAAAAAAAAAAAACAwABBAUGEjKh/8QAFQEBAQAAAAAAAAAAAAAAAAAABAX/xAAXEQEBAQEAAAAAAAAAAAAAAAABAgAD/9oADAMBAAIRAxEAPwCef6Le7Rm0Ye5y0CnMvHWpIr8RAACq9hu/sREj9YltUzudJIDv/9k="
  },
  {
    id: 4,
    name: "Steampunk",
    is_visible: true,
    created_at: "2021-10-12T19:10:20.201107+00:00",
    updated_at: "2022-03-08T05:09:17.414243+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/steampunk.jpg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAfEAAABgIDAQAAAAAAAAAAAAAAAQIDBAUREwdBUXH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBf/EABgRAQEBAQEAAAAAAAAAAAAAAAECAAMh/9oADAMBAAIRAxEAPwC54zeTbw76TZxo8l0rqW0jY3nWhK8ElPhd/TMAAJxiWBTWX3f/2Q=="
  },
  {
    id: 20,
    name: "Blacklight",
    is_visible: true,
    created_at: "2022-02-16T23:01:20.215329+00:00",
    updated_at: "2022-03-08T05:09:17.414243+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/backlight.jpg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAdEAABBAIDAAAAAAAAAAAAAAABAAIFBgMEETFB/8QAFQEBAQAAAAAAAAAAAAAAAAAABAX/xAAaEQABBQEAAAAAAAAAAAAAAAAAAQIDEjJR/9oADAMBAAIRAxEAPwCohqlCWap1qWlNDG7c2YvA7I5hLQTweh4iIrV3dByaU//Z"
  },
  {
    id: 18,
    name: "Rose Gold",
    is_visible: true,
    created_at: "2022-01-17T22:10:36.750442+00:00",
    updated_at: "2022-03-08T05:09:17.414243+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/rose-gold-thumbnail.jpeg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAfEAAABQQDAAAAAAAAAAAAAAAAAQIDBAUGERMVJDH/xAAVAQEBAAAAAAAAAAAAAAAAAAAFBv/EABkRAQACAwAAAAAAAAAAAAAAAAEAAhESIf/aAAwDAQACEQMRAD8Aml8XDWYFYaY5SXI6rKtj7hqUeUkfpYAABlQxK7exwZ//2Q=="
  },
  {
    id: 16,
    name: "Wuhtercuhler",
    is_visible: true,
    created_at: "2022-01-07T03:36:37.058860+00:00",
    updated_at: "2022-03-08T05:09:17.414243+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/watercolor.jpg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAeEAACAgICAwAAAAAAAAAAAAABAgMEAAYFUREhMf/EABUBAQEAAAAAAAAAAAAAAAAAAAQG/8QAGREAAgMBAAAAAAAAAAAAAAAAAQIAAxEh/9oADAMBAAIRAxEAPwCDqu1Xdj4oW70NWNkcxJHXVo0RR78AA9sfveMYwodsHZXrYyjAcE//2Q=="
  },
  {
    id: 21,
    name: "Psychedelic",
    is_visible: true,
    created_at: "2022-03-08T04:45:45.191477+00:00",
    updated_at: "2022-03-08T04:45:45.191477+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/lisa.jpg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAfEAABBAICAwAAAAAAAAAAAAABAAIEBQMhERIHIkH/xAAUAQEAAAAAAAAAAAAAAAAAAAAE/8QAGhEAAgIDAAAAAAAAAAAAAAAAAAIBAxIhUf/aAAwDAQACEQMRAD8An3lOXLq7aokVsuTGNrUxbGSxuUlpzZG+xHbkgHqNc6+aRESa2bGNjZdun//Z"
  },
  {
    id: 2,
    name: "Ukiyoe",
    is_visible: true,
    created_at: "2021-10-11T17:56:22.084836+00:00",
    updated_at: "2021-12-03T00:57:10.269924+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/ukiyoe.jpg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAeEAACAgEFAQAAAAAAAAAAAAABAgADBAcREhQhBf/EABQBAQAAAAAAAAAAAAAAAAAAAAX/xAAXEQADAQAAAAAAAAAAAAAAAAAAAREx/9oADAMBAAIRAxEAPwCnaMr29NvjZyHq2ZiPdbXQAE5c2XcAg7eKPIiII9FYj//Z"
  },
  {
    id: 1,
    name: "Synthwave",
    is_visible: true,
    created_at: "2021-10-11T17:55:51.462768+00:00",
    updated_at: "2021-12-03T00:57:10.269924+00:00",
    deleted_at: null,
    photo_url: "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/synthwave.jpg",
    is_premium: false,
    model_type: "vqgan",
    is_new: false,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAeEAACAgICAwAAAAAAAAAAAAABAgADBBEFBhQhMf/EABUBAQEAAAAAAAAAAAAAAAAAAAQF/8QAGREAAgMBAAAAAAAAAAAAAAAAAQIAAxIR/9oADAMBAAIRAxEAPwChdD6vw+Nw9yW4nlu17Obcqx7LCWCk7bez7J+xER1hOjLL2MjZU8E//9k="
  }
]
